
module.exports = {
    async up(queryInterface, Sequelize) {
      await queryInterface.bulkInsert(
       "products", [

  // Categoría 1
      {
        title: "Fundamentos de la Ciberseguridad",
        subtitle: "Comienza tu camino",
        language_id: 1,
        category_id: 1,
        subcategory_id: 0,
        description: "Introducción a los conceptos clave de la ciberseguridad moderna.",
        price: 80,
        available: 1,
        image: "course1746414737695.png",
        rating: 4.2,
        reviews: 15,
        timesBought: 50,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Conceptos Básicos de Seguridad",
        subtitle: "La base de todo",
        language_id: 3,
        category_id: 1,
        subcategory_id: 0,
        description: "Aprende los principios que sustentan la seguridad informática.",
        price: 70,
        available: 1,
        image: "course1746299611832.jpg",
        rating: 4.0,
        reviews: 10,
        timesBought: 34,
        user_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Panorama de la Seguridad Digital",
        subtitle: "Entiende el ecosistema",
        language_id: 5,
        category_id: 1,
        subcategory_id: 0,
        description: "Explora cómo funciona el mundo de la seguridad digital a nivel global.",
        price: 85,
        available: 1,
        image: "course1747164425316.png",
        rating: 4.3,
        reviews: 18,
        timesBought: 41,
        user_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Categoría 2 (Ofensiva)
      {
        title: "Curso Avanzado de Web Hacking",
        subtitle: "Desde inyecciones hasta XSS",
        language_id: 2,
        category_id: 2,
        subcategory_id: 1,
        description: "Aprende técnicas modernas de hacking web con prácticas reales.",
        price: 120,
        available: 1,
        image: "default.png",
        rating: 4.5,
        reviews: 30,
        timesBought: 120,
        user_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Pentesting Profesional",
        subtitle: "Evalúa vulnerabilidades como un pro",
        language_id: 3,
        category_id: 2,
        subcategory_id: 2,
        description: "Desarrolla habilidades de análisis y explotación en entornos controlados.",
        price: 180,
        available: 1,
        image: "default.png",
        rating: 4.7,
        reviews: 45,
        timesBought: 95,
        user_id: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Exploit Development",
        subtitle: "Desde cero hasta buffer overflows",
        language_id: 1,
        category_id: 2,
        subcategory_id: 3,
        description: "Domina la creación y ejecución de exploits paso a paso.",
        price: 200,
        available: 1,
        image: "default.png",
        rating: 4.9,
        reviews: 60,
        timesBought: 80,
        user_id: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Categoría 3 (Defensiva)
      {
        title: "Fortificación de Redes",
        subtitle: "Blindaje ante ciberataques",
        language_id: 4,
        category_id: 3,
        subcategory_id: 4,
        description: "Aprende a proteger redes con técnicas de hardening y firewalls.",
        price: 140,
        available: 1,
        image: "default.png",
        rating: 4.4,
        reviews: 25,
        timesBought: 100,
        user_id: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Respuesta a Incidentes",
        subtitle: "Actúa en tiempo real",
        language_id: 5,
        category_id: 3,
        subcategory_id: 5,
        description: "Curso práctico sobre cómo manejar incidentes de seguridad reales.",
        price: 160,
        available: 1,
        image: "default.png",
        rating: 4.6,
        reviews: 33,
        timesBought: 76,
        user_id: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Malware Analysis",
        subtitle: "Rompe el código malicioso",
        language_id: 2,
        category_id: 3,
        subcategory_id: 6,
        description: "Aprende análisis estático y dinámico de malware real.",
        price: 190,
        available: 1,
        image: "default.png",
        rating: 4.8,
        reviews: 50,
        timesBought: 89,
        user_id: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Categoría 4 (Nube)
      {
        title: "Control de Accesos en la Nube",
        subtitle: "IAM de forma segura",
        language_id: 1,
        category_id: 4,
        subcategory_id: 7,
        description: "Gestiona permisos y usuarios en entornos cloud.",
        price: 150,
        available: 1,
        image: "default.png",
        rating: 4.3,
        reviews: 28,
        timesBought: 65,
        user_id: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Arquitectura Segura AWS",
        subtitle: "Construye infraestructura segura",
        language_id: 3,
        category_id: 4,
        subcategory_id: 8,
        description: "Buenas prácticas y herramientas para diseñar sistemas seguros.",
        price: 170,
        available: 1,
        image: "default.png",
        rating: 4.6,
        reviews: 35,
        timesBought: 72,
        user_id: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Respuesta a Incidentes en Cloud",
        subtitle: "Detección y contención",
        language_id: 4,
        category_id: 4,
        subcategory_id: 9,
        description: "Preparación, detección y reacción ante ataques en cloud.",
        price: 180,
        available: 1,
        image: "default.png",
        rating: 4.7,
        reviews: 38,
        timesBought: 84,
        user_id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      // Categoría 5 (Ingeniería Social)
      {
        title: "Técnicas de Ingeniería Social",
        subtitle: "El arte de manipular",
        language_id: 2,
        category_id: 5,
        subcategory_id: 10,
        description: "Aprende cómo los atacantes manipulan a las personas.",
        price: 100,
        available: 1,
        image: "default.png",
        rating: 4.2,
        reviews: 22,
        timesBought: 55,
        user_id: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Concientización de Seguridad",
        subtitle: "Educando para prevenir",
        language_id: 3,
        category_id: 5,
        subcategory_id: 11,
        description: "Entrena al personal para detectar amenazas sociales.",
        price: 90,
        available: 1,
        image: "default.png",
        rating: 4.1,
        reviews: 19,
        timesBought: 48,
        user_id: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Simulaciones de Phishing",
        subtitle: "Prevención efectiva",
        language_id: 5,
        category_id: 5,
        subcategory_id: 10,
        description: "Pon a prueba a tu equipo con simulaciones realistas.",
        price: 95,
        available: 1,
        image: "default.png",
        rating: 4.3,
        reviews: 24,
        timesBought: 53,
        user_id: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
],

        {}
      );
    },
  
    async down(queryInterface, Sequelize) {
      await queryInterface.bulkDelete("products", null, {});
    },
  };